# version: '3'
# services:
#   prisma:
#     image: prismagraphql/prisma:1.32
#     restart: always
#     ports:
#       - '4466:4466'
#     environment:
#       PRISMA_CONFIG: |
#         port: 4466
#         databases:
#           default:
#             connector: postgres
#             host: postgres
#             port: 5432
#             user: prisma
#             password: prisma
#   postgres:
#     image: postgres:10.3
#     restart: always
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#     volumes:
#       - /Users/techoi/Techoi/side/graphql/prisma-mysql/postgres:/var/lib/postgresql/data
# volumes:
#   postgres: ~

version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
            rawAccess: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - /Users/techoi/Techoi/side/graphql/prisma-mysql/mysql:/var/lib/mysql
volumes:
  mysql: